// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twcandgazzzbbrmffstt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3Y2FuZGdhenp6YmJybWZmc3R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NjIxMTgsImV4cCI6MjA2MzQzODExOH0.vYKHCLERTTzeshRpNy5Wr_sZ2bezW2Yz7BaY149MTcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);